export const users = [
  {
    id: 1,
    name: "Jacquenetta Slowgrave",
    status: "online",
    lastMsg: "Great! Looking forward to it. Se...",
    time: "10 minutes",
    unread: 8,
  },
  {
    id: 2,
    name: "Nickola Peever",
    status: "offline",
    lastMsg: "Sounds perfect! I've been wantin...",
    time: "40 minutes",
    unread: 2,
  },
  {
    id: 3,
    name: "Farand Hume",
    status: "offline",
    lastMsg: "How about 7 PM at the new Italian pla...",
    time: "Yesterday",
    unread: 0,
  },
  {
    id: 4,
    name: "Ossie Peasey",
    status: "offline",
    lastMsg: "Hey Bonnie, yes, definitely! What time...",
    time: "13 days",
    unread: 0,
  },
  {
    id: 5,
    name: "Hall Negri",
    status: "online",
    lastMsg: "No worries at all! I'll grab a table and ...",
    time: "2 days",
    unread: 0,
  },
  {
    id: 6,
    name: "Jack doe",
    status: "online",
    lastMsg: "Great! Looking forward to it. Se...",
    time: "10 minutes",
    unread: 8,
  },
  {
    id: 7,
    name: "Nike Peever",
    status: "offline",
    lastMsg: "Sounds perfect! I've been wantin...",
    time: "40 minutes",
    unread: 2,
  },
  {
    id: 8,
    name: "Farhad Yum",
    status: "offline",
    lastMsg: "How about 7 PM at the new Italian pla...",
    time: "Yesterday",
    unread: 999,
  },
  {
    id: 9,
    name: "Ashu Pasu",
    status: "offline",
    lastMsg: "Hey Bonnie, yes, definitely! What time...",
    time: "13 days",
    unread: 0,
  },
  {
    id: 10,
    name: "Ankit Negi",
    status: "online",
    lastMsg: "No worries at all! I'll grab a table and ...",
    time: "2 days",
    unread: 0,
  },
  {
    id: 11,
    name: "Jasmin Patgiri",
    status: "online",
    lastMsg: "Great! Looking forward to it. Se...",
    time: "10 minutes",
    unread: 8,
  },
  {
    id: 12,
    name: "Nipni Peever",
    status: "offline",
    lastMsg: "Sounds perfect! I've been wantin...",
    time: "40 minutes",
    unread: 2,
  },
  {
    id: 13,
    name: "Farhana Choudary",
    status: "offline",
    lastMsg: "How about 7 PM at the new Italian pla...",
    time: "Yesterday",
    unread: 0,
  },
  {
    id: 14,
    name: "Jamal Dutta",
    status: "offline",
    lastMsg: "Hey Bonnie, yes, definitely! What time...",
    time: "13 days",
    unread: 0,
  },
  {
    id: 15,
    name: "Priya Sharma",
    status: "online",
    lastMsg: "No worries at all! I'll grab a table and ...",
    time: "2 days",
    unread: 0,
  },
];
